###### Main Service ######
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: auth-deployment
    spec:
      containers:
      - name: authservice-java
        image: authservice-java:latest 
        ports:
          - containerPort: 9080
        imagePullPolicy: IfNotPresent
        env:
        - name: CUSTOMER_SERVICE
          value: customer-service:9080
        - name: MB_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mb-keystore-password
              key: password
        - name: MB_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mb-truststore-password
              key: password
        volumeMounts:
          - name: keystores
            mountPath: /etc/wlp/config/keystore
            readOnly: true
          - name: truststores
            mountPath: /etc/wlp/config/truststore
            readOnly: true
          - name: liberty-config
            mountPath: /config/configDropins
      volumes:
        - name: keystores
          secret:
            secretName: mb-keystore
        - name: truststores
          secret:
            secretName: mb-truststore
        - name: liberty-config
          configMap:
            name: liberty-logging-config
            items:
              - key: keystore.xml
                path: defaults/keystore.xml
              - key: logging.xml
                path: defaults/logging.xml
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
spec:
  ports:
    - port: 9080
  selector:
    name: auth-deployment
